CREATE DATABASE EDUCATA;

CREATE TABLE AFFECTATION_COURS
(
	CODE_ENSEIGNANT       varchar(20) NOT NULL,
	CODE_COURS            VARCHAR(20) NOT NULL,
	CODE_VACATION         VARCHAR(20) NOT NULL,
	DATE_AFFECTATION      DATE NOT NULL,
	MEMO                  VARCHAR(200) NULL,
	TYPE_SALAIRE          VARCHAR(20) NULL DEFAULT 'MENSUEL'
		CONSTRAINT  TYPE_SALAIRE CHECK (TYPE_SALAIRE IN('MENSUEL','HEBDOMADAIRE','QUIZAINE','JOURNALIER','HORAIRE')),
	MONTANT_SALAIRE       INTEGER NOT NULL DEFAULT 0,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL,
	DEVISE_ID             VARCHAR(3) NULL
)
;


ALTER TABLE AFFECTATION_COURS
	ADD  PRIMARY KEY (CODE_ENSEIGNANT,CODE_COURS,CODE_VACATION)
;



CREATE TABLE APPRENANT
(
	CODE_APPRENANT        varchar(20) NOT NULL,
	DATE_INSCRIPTION      date NULL,
	DATE_NAISSANCE        date NOT NULL,
	ETAT_CIVIL            varchar(1) NOT NULL,
	SEXE                  varchar(1) NOT NULL,
	STATUT                varchar(20) NOT NULL,
	NOM_PERE              varchar(50) NULL,
	NOM_MERE              varchar(50) NULL,
	NOM_CONJOINT          varchar(50) NULL,
	PIECE                 varchar(15) NOT NULL,
	NO_PIECE              varchar(40) NOT NULL,
	TELEPHONE_1           varchar(25) NOT NULL,
	TELEPHONE_2           varchar(25) NULL,
	TELEPHONE_3           varchar(25) NULL,
	COURRIEL              varchar(40) NULL,
	NATIONALITE           varchar(15) NULL,
	NOM                   varchar(30) NOT NULL,
	NOM_JEUNE_FILLE       varchar(30) NULL,
	PRENOM                varchar(30) NOT NULL,
	ADRESSE               varchar(75) NULL,
	REMARQUE              varchar(128) NULL,
	ADRESSE_POSTALE       varchar(75) NULL,
	AUTRE_INFORMATION     varchar(2000) NULL,
	LOCALISATION          varchar(100) NULL,
	PERSONNE_CONTACT      varchar(50) NULL,
	TELEPHONE_CONTACT     varchar(50) NULL,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWSCN                INTEGER NOT NULL,
	ROWID                 varchar(128) NOT NULL,
	PHOTO                 VARCHAR(200) NULL,
	MOYEN_TRANSPORT       VARCHAR(20) NULL
		CONSTRAINT  MOYEN_TRANSPORT CHECK (MOYEN_TRANSPORT IN('PUBLIC','VOITURE','MOTO','VELO','PIED','AUTRE')),
	NO_BADGE              VARCHAR(20) NULL,
	COURRIEL_ALT          VARCHAR(20) NULL,
	CODE_VILLE_NAISSANCE  VARCHAR(20) NULL,
	CODE_ETAT_NAISSANCE   VARCHAR(20) NULL,
	CODE_PAYS_NAISSANCE   VARCHAR(20) NULL,
	CODE_VILLE_HABITATION  VARCHAR(20) NULL,
	CODE_ETAT_HABITATION  VARCHAR(20) NULL,
	CODE_PAYS_HABITATION  VARCHAR(20) NULL
)
;



ALTER TABLE APPRENANT
	ADD  PRIMARY KEY (CODE_APPRENANT)
;



CREATE UNIQUE INDEX EMPLOYE_ROWID_UQ ON APPRENANT
(
	ROWID
)
;



CREATE TABLE AUTORISATION
(
	AUTORISATEUR          VARCHAR(20) NOT NULL,
	REFERENCE             VARCHAR(120) NOT NULL,
	AUTORISATION_NO       INTEGER NOT NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	STATUT                VARCHAR(20) NULL DEFAULT 'NOUVEAU'
		CONSTRAINT  STATUT CHECK (STATUT IN('NOUVEAU','REFUSE','AUTORISE')),
	DATE_AUTORISATION     DATE NOT NULL,
	USER_ID               VARCHAR(20) NULL,
	DATE_DEMANDE          DATE NULL,
	_default_             CHAR(18) NULL
)
;



ALTER TABLE AUTORISATION
	ADD  PRIMARY KEY (AUTORISATION_NO)
;



CREATE UNIQUE INDEX AUTO_ROWID_UQ ON AUTORISATION
(
	ROWID
)
;



CREATE TABLE CHOIX_COURS
(
	CODE_APPRENANT        varchar(20) NOT NULL,
	DATE_CHOIX            DATE NULL,
	CODE_COURS            VARCHAR(20) NOT NULL,
	MENTION               VARCHAR(60) NULL,
	NOTE                  DECIMAL(22,2) NOT NULL DEFAULT 0,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL
)
;



ALTER TABLE CHOIX_COURS
	ADD  PRIMARY KEY (CODE_APPRENANT,CODE_COURS)
;



CREATE TABLE COURS
(
	CODE_COURS            VARCHAR(20) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	CODE_MATIERE          VARCHAR(20) NULL,
	CODE_NIVEAU           VARCHAR(20) NULL,
	COEFFICIENT           INTEGER NOT NULL DEFAULT 1,
	OBLIGATOIRE           VARCHAR(20) NULL DEFAULT 'Y'
		CONSTRAINT  OBLIGATOIRE CHECK (OBLIGATOIRE IN('Y','N')),
	ACTIF                 VARCHAR(1) NOT NULL DEFAULT 'Y'
		CONSTRAINT  ACTIF CHECK (ACTIF IN('Y','N')),
	DATE_CREATION         DATE NOT NULL,
	DATE_STATUT           DATE NULL,
	NB_CREDIT             INTEGER NOT NULL DEFAULT 0,
	PREREQUIS             VARCHAR(20) NULL,
	CODE_OPTION           VARCHAR(20) NULL
)
;



ALTER TABLE COURS
	ADD  PRIMARY KEY (CODE_COURS)
;



CREATE UNIQUE INDEX COURS_ROWID_UQ ON COURS
(
	ROWID
)
;



CREATE TABLE DEVISE
(
	DEVISE_ID             VARCHAR(3) NOT NULL,
	DESCRIPTION           VARCHAR(40) NOT NULL,
	SIGNE                 VARCHAR(3) NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	CHANGE                VARCHAR(1) NOT NULL DEFAULT 'N'
		CONSTRAINT  CHANGE CHECK (CHANGE IN('Y','N'))
)
;



ALTER TABLE DEVISE
	ADD  PRIMARY KEY (DEVISE_ID)
;



CREATE UNIQUE INDEX DEVISE_ROWID_UQ ON DEVISE
(
	ROWID
)
;



CREATE INDEX DEVISE_CUSER_IX ON DEVISE
(
	CREATED_BY
)
;



CREATE INDEX DEVISE_CDATE_IX ON DEVISE
(
	CREATED_ON
)
;



CREATE TABLE DOCUMENT_FOURNI
(
	DATE_RECEPTION        DATE NULL,
	REMARQUE              VARCHAR(100) NULL,
	CODE_APPRENANT        varchar(20) NOT NULL,
	TYPE_DOCUMENT         VARCHAR(20) NOT NULL,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL,
	DOCUMENT              VARCHAR(256) NOT NULL
)
;



ALTER TABLE DOCUMENT_FOURNI
	ADD  PRIMARY KEY (CODE_APPRENANT,TYPE_DOCUMENT)
;



CREATE TABLE ENSEIGNANT
(
	CODE_ENSEIGNANT       varchar(20) NOT NULL,
	DATE_INSCRIPTION      date NULL,
	DATE_NAISSANCE        date NOT NULL,
	ETAT_CIVIL            varchar(1) NOT NULL,
	SEXE                  varchar(1) NOT NULL,
	STATUT                varchar(20) NOT NULL,
	NOM_PERE              varchar(50) NULL,
	NOM_MERE              varchar(50) NULL,
	NOM_CONJOINT          varchar(50) NULL,
	PIECE                 varchar(15) NOT NULL,
	NO_PIECE              varchar(40) NOT NULL,
	TELEPHONE_1           varchar(25) NOT NULL,
	TELEPHONE_2           varchar(25) NULL,
	TELEPHONE_3           varchar(25) NULL,
	COURRIEL              varchar(40) NULL,
	NATIONALITE           varchar(15) NULL,
	NOM                   varchar(30) NOT NULL,
	NOM_JEUNE_FILLE       varchar(30) NULL,
	PRENOM                varchar(30) NOT NULL,
	ADRESSE               varchar(75) NULL,
	REMARQUE              varchar(128) NULL,
	ADRESSE_POSTALE       varchar(75) NULL,
	AUTRE_INFORMATION     varchar(2000) NULL,
	LOCALISATION          varchar(100) NULL,
	PERSONNE_CONTACT      varchar(50) NULL,
	TELEPHONE_CONTACT     varchar(50) NULL,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWSCN                INTEGER NOT NULL,
	ROWID                 varchar(128) NOT NULL,
	PHOTO                 VARCHAR(200) NULL,
	MOYEN_TRANSPORT       VARCHAR(20) NULL
		CONSTRAINT  MOYEN_TRANSPORT CHECK (MOYEN_TRANSPORT IN('PUBLIC','VOITURE','MOTO','VELO','PIED','AUTRE')),
	NO_BADGE              VARCHAR(20) NULL,
	COURRIEL_ALT          VARCHAR(20) NULL,
	CODE_VILLE_NAISSANCE  VARCHAR(20) NULL,
	CODE_ETAT_NAISSANCE   VARCHAR(20) NULL,
	CODE_PAYS_NAISSANCE   VARCHAR(20) NULL,
	CODE_VILLE_HABITATION  VARCHAR(20) NULL,
	CODE_ETAT_HABITATION  VARCHAR(20) NULL,
	CODE_PAYS_HABITATION  VARCHAR(20) NULL,
	MONTANT_SALAIRE       INTEGER NOT NULL DEFAULT 0,
	TYPE_SALAIRE          VARCHAR(20) NULL DEFAULT 'MENSUEL'
		CONSTRAINT  TYPE_SALAIRE CHECK (TYPE_SALAIRE IN('MENSUEL','HEBDOMADAIRE','QUIZAINE','JOURNALIER','HORAIRE')),
	DEVISE_ID             VARCHAR(3) NULL
)
;



ALTER TABLE ENSEIGNANT
	ADD  PRIMARY KEY (CODE_ENSEIGNANT)
;



CREATE UNIQUE INDEX EMPLOYE_ROWID_UQ ON ENSEIGNANT
(
	ROWID
)
;



CREATE TABLE ETAT
(
	CODE_ETAT             VARCHAR(20) NOT NULL,
	NOM                   VARCHAR(20) NOT NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	CODE_PAYS             VARCHAR(20) NOT NULL
)
;



ALTER TABLE ETAT
	ADD  PRIMARY KEY (CODE_ETAT,CODE_PAYS)
;



CREATE UNIQUE INDEX ETAT_ROWID_UQ ON ETAT
(
	ROWID
)
;



CREATE TABLE ETUDE_ANTERIEURE
(
	DATE_DEBUT            date NOT NULL,
	DATE_FIN              date NOT NULL,
	TITRE                 varchar(100) NOT NULL,
	ETABLISSEMENT         varchar(100) NOT NULL,
	REMARQUE              varchar(100) NULL,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWSCN                INTEGER NOT NULL,
	ROWID                 varchar(128) NOT NULL,
	NO_SEQ                INTEGER NULL,
	CODE_APPRENANT        varchar(20) NOT NULL,
	SUCCES                VARCHAR(20) NOT NULL DEFAULT 'Y'
		CONSTRAINT  SUCCES CHECK (SUCCESS IN('Y','N')),
	MOYENNE               DECIMAL(22,2) NOT NULL DEFAULT 0,
	MOYENNE_PASSAGE       DECIMAL(22,2) NULL
)
;



ALTER TABLE ETUDE_ANTERIEURE
	ADD  PRIMARY KEY (DATE_DEBUT,DATE_FIN,NO_SEQ,CODE_APPRENANT)
;



CREATE UNIQUE INDEX FORMATION_ROWID_UQ ON ETUDE_ANTERIEURE
(
	ROWID
)
;



CREATE TABLE EXPERIENCE
(
	POSTE                 varchar(100) NOT NULL,
	PAYS                  varchar(4) NOT NULL,
	FIRME                 varchar(50) NOT NULL,
	MONNAIE_SALAIRE       varchar(4) NULL,
	SALAIRE               1(12) NULL,
	NIVEAU                varchar(50) NULL,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWSCN                INTEGER NOT NULL,
	ROWID                 varchar(128) NOT NULL,
	NOTE                  VARCHAR(200) NULL
)
;



CREATE UNIQUE INDEX EXPERIENCE_ROWID_UQ ON EXPERIENCE
(
	ROWID
)
;



CREATE TABLE INSTITUTION
(
	INSTITUTION_ID        INTEGER NULL,
	NOM_INSTITUTION       VARCHAR(20) NOT NULL,
	DATE_CREATION         DATE NULL,
	ADRESSE               VARCHAR(120) NULL,
	TELEPHONE1            VARCHAR(20) NOT NULL,
	TELEPHONE2            VARCHAR(20) NULL,
	TELEPHONE3            VARCHAR(20) NULL,
	COURRIEL              VARCHAR(20) NULL,
	TYPE_INSTITUTION      VARCHAR(20) NOT NULL,
	NOM_REPONSABLE        CHAR(18) NOT NULL,
	PRENOM_RESPONSABLE    VARCHAR(20) NOT NULL,
	EXTENSION_RESPONSABLE  VARCHAR(20) NULL,
	COURRIEL_RESPONSABLE  VARCHAR(20) NULL,
	TITRE_RESPONSABLE     VARCHAR(20) NULL,
	SEXE_RESPONSABLE      VARCHAR(20) NULL,
	MODALITE_PAIEMENT     VARCHAR(20) NOT NULL,
	TYPE_PAIEMENT         VARCHAR(20) NULL,
	STATUT                VARCHAR(20) NOT NULL,
	DELAI_GRACE           INTEGER NULL,
	NOM_CONTACT           VARCHAR(20) NULL,
	PRENOM_CONTACT        VARCHAR(20) NULL,
	COURRIEL_CONTACT      VARCHAR(20) NULL,
	TELEPHONE_CONTACT     VARCHAR(20) NULL,
	TELEPHONE_RESPONSABLE  VARCHAR(20) NULL,
	TITRE_CONTACT         VARCHAR(20) NULL,
	INSTITUTION_PARENTE   VARCHAR(20) NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	LOGO                  VARCHAR(120) NULL,
	DEVISE_LOCALE         VARCHAR(3) NULL,
	TAUX_TVA              DECIMAL(22,2) NOT NULL DEFAULT 0,
	LONG_MIN_RECHERCHE    INTEGER NOT NULL DEFAULT 4,
	MESSAGE_RECU1         VARCHAR(120) NULL,
	MESSAGE_RECU2         VARCHAR(120) NULL,
	MESSAGE_RECU3         VARCHAR(120) NULL,
	DASHBOARD_PLAGE_REC   VARCHAR(20) NULL DEFAULT 'JOUR'
		CONSTRAINT  DASHBOARD_PLAGE_REC CHECK (DASHBOARD_PLAGE_REC IN('JOUR','SEMAINE','MOIS','ANNEE')),
	DASHBOARD_REL_DELAY   INTEGER NULL DEFAULT 300000,
	NOTE_MAX              INTEGER NOT NULL DEFAULT 100,
	MOYENNE_PASSE         INTEGER NOT NULL,
	MOYENNE_REPRISE       INTEGER NOT NULL
)
;



ALTER TABLE INSTITUTION
	ADD  PRIMARY KEY (INSTITUTION_ID)
;



CREATE UNIQUE INDEX USER_INST_ROWID_UQ ON INSTITUTION
(
	ROWID
)
;



CREATE INDEX INST_DATE_IX ON INSTITUTION
(
	CREATED_ON
)
;



CREATE INDEX INST_USER_IX ON INSTITUTION
(
	CREATED_BY
)
;



CREATE TABLE LOG_ACCESS
(
	USER_ID               VARCHAR(20) NOT NULL,
	DATE_ACCESS           TIMESTAMP NOT NULL,
	ECRAN                 VARCHAR(120) NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	LOG_NO                INTEGER NULL
)
;



ALTER TABLE LOG_ACCESS
	ADD  PRIMARY KEY (LOG_NO)
;



CREATE INDEX LOG_ACCESS_USER_DATE_IK ON LOG_ACCESS
(
	USER_ID,
	DATE_ACCESS
)
;



CREATE INDEX LOG_ACCESS_USER_IK ON LOG_ACCESS
(
	USER_ID
)
;



CREATE INDEX LOG_ACCESS_DATE_IK ON LOG_ACCESS
(
	DATE_ACCESS
)
;



CREATE INDEX LOG_ACCESS_CREATION_DATE_IK ON LOG_ACCESS
(
	CREATED_BY
)
;



CREATE INDEX LOG_ACCESS_ROWID_IK ON LOG_ACCESS
(
	ROWID
)
;



CREATE TABLE MATIERE
(
	CODE_MATIERE          VARCHAR(20) NOT NULL,
	DESIGNATION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0
)
;



ALTER TABLE MATIERE
	ADD  PRIMARY KEY (CODE_MATIERE)
;



CREATE UNIQUE INDEX MATIER_ROWID_UQ ON MATIERE
(
	ROWID
)
;



CREATE TABLE NIVEAU
(
	CODE_NIVEAU           VARCHAR(20) NOT NULL,
	DESIGNATION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	OPTION_PAIEMENT       CHAR(18) NULL DEFAULT 'TRANCHE'
		CONSTRAINT  OPTION_PAIEMENT CHECK (MODE_PAIEMENT IN('CREDIT','MENSUEL','TRANCHE','TRIMESTRIEL','SEMESTRIEL','ANNUEL')),
	MONTANT_OBLIGATION    DECIMAL(22,2) NOT NULL DEFAULT 0,
	DATE_PAIEM_OBLIGATION  DATE NULL,
	DEVISE_ID             VARCHAR(3) NULL
)
;



ALTER TABLE NIVEAU
	ADD  PRIMARY KEY (CODE_NIVEAU)
;



CREATE UNIQUE INDEX NIVEAU_ROWID_UQ ON NIVEAU
(
	ROWID
)
;



CREATE TABLE OPTION
(
	DESIGNATION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	CODE_OPTION           VARCHAR(20) NOT NULL
)
;



ALTER TABLE OPTION
	ADD  PRIMARY KEY (CODE_OPTION)
;



CREATE UNIQUE INDEX OPTION_ROWID_UQ ON OPTION
(
	ROWID
)
;



CREATE TABLE PACOURS_APPRENANT
(
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL,
	DATE_DEBUT            DATE NULL,
	DATE_FIN              DATE NULL,
	CODE_APPRENANT        varchar(20) NOT NULL,
	CODE_NIVEAU           VARCHAR(20) NULL,
	CODE_SALLE            VARCHAR(20) NULL,
	CODE_VACATION         VARCHAR(20) NULL,
	CODE_OPTION           VARCHAR(20) NULL,
	ACTIF                 VARCHAR(1) NOT NULL DEFAULT 'N'
		CONSTRAINT  ACTIF CHECK (ACTIF IN('Y','N')),
	REMARQUES             VARCHAR(1000) NULL
)
;



ALTER TABLE PACOURS_APPRENANT
	ADD  PRIMARY KEY (CODE_APPRENANT,DATE_DEBUT)
;



CREATE TABLE PAIEMENT
(
	NO_PAIEMENT           INTEGER NOT NULL,
	NOTES                 VARCHAR(200) NULL,
	STATUT                VARCHAR(20) NOT NULL DEFAULT 'NOUVEAU'
		CONSTRAINT  STATUT CHECK (STATUT IN('NOUVEAU','EN COURS','FINALISE')),
	MONTANT               DECIMAL(22,2) NOT NULL DEFAULT 0,
	BALANCE               DECIMAL(22,2) NOT NULL DEFAULT 0,
	DATE_PAIEMENT         DATE NOT NULL,
	CODE_APPRENANT        varchar(20) NULL,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL,
	DEVISE_ID             VARCHAR(3) NULL
)
;



ALTER TABLE PAIEMENT
	ADD  PRIMARY KEY (NO_PAIEMENT)
;



CREATE TABLE PARAM_INOUT
(
	PARAM_INOUT_ID        VARCHAR(20) NOT NULL,
	DESCRIPTION           VARCHAR(80) NOT NULL,
	VALEUR                VARCHAR(15000) NOT NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0
)
;



ALTER TABLE PARAM_INOUT
	ADD  PRIMARY KEY (PARAM_INOUT_ID)
;



CREATE UNIQUE INDEX PARAM_INOUT_ROWID_UQ ON PARAM_INOUT
(
	ROWID
)
;



CREATE TABLE PAYS
(
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	CODE_PAYS             VARCHAR(20) NOT NULL,
	NOM                   VARCHAR(20) NOT NULL
)
;



ALTER TABLE PAYS
	ADD  PRIMARY KEY (CODE_PAYS)
;



CREATE UNIQUE INDEX PAYS_ROWID_UQ ON PAYS
(
	ROWID
)
;



CREATE TABLE SALLE
(
	CODE_SALLE            VARCHAR(20) NOT NULL,
	DESCRIPTION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0
)
;



ALTER TABLE SALLE
	ADD  PRIMARY KEY (CODE_SALLE)
;



CREATE UNIQUE INDEX SALLE_ROWID_UQ ON SALLE
(
	ROWID
)
;



CREATE TABLE SUIVI_APPRENANT
(
	NO_SEQ                INTEGER NOT NULL,
	REMARQUE              VARCHAR(2000) NOT NULL,
	GRAVITE               VARCHAR(20) NOT NULL DEFAULT 'NEUTRE'
		CONSTRAINT  GRAVITE CHECK (GRAVITE IN('NEUTRE','GRAVE','MOYEN','PAS GRAVE')),
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWSCN                INTEGER NOT NULL,
	ROWID                 varchar(128) NOT NULL,
	DATE_INFO             DATE NOT NULL,
	CODE_APPRENANT        varchar(20) NULL
)
;



ALTER TABLE SUIVI_APPRENANT
	ADD  PRIMARY KEY (NO_SEQ)
;



CREATE UNIQUE INDEX AUTREINF_ROWID_UQ ON SUIVI_APPRENANT
(
	ROWID
)
;



CREATE TABLE TAUX
(
	DATE_TAUX             DATE NOT NULL,
	TAUX_INTERNE          DECIMAL(22,6) NOT NULL DEFAULT 0,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	DEVISE_ID             VARCHAR(3) NOT NULL
)
;



ALTER TABLE TAUX
	ADD  PRIMARY KEY (DEVISE_ID,DATE_TAUX)
;



CREATE UNIQUE INDEX TAUX_ROWID_UQ ON TAUX
(
	ROWID
)
;



CREATE INDEX TAUX_CDATE_IX ON TAUX
(
	CREATED_ON
)
;



CREATE INDEX TAUX_CUSER_IX ON TAUX
(
	CREATED_BY
)
;



CREATE TABLE TRANCHE_PAIMENT_PARAM
(
	DESCRIPTION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	NO_SEQ                INTEGER NULL,
	CODE_NIVEAU           VARCHAR(20) NULL,
	DATE_MIN              DATE NULL,
	DATE_MAX              DATE NULL,
	MONTANT_PENALITE      DECIMAL(22,2) NOT NULL DEFAULT 0,
	FREQUENCE_PENALITE    INTEGER NULL
		CONSTRAINT  FREQUENCE_PENALITE CHECK (FREQUENCE_PENALITE IN('JOUR','SEMAINE','MOIS')),
	CODE_VACATION         VARCHAR(20) NULL,
	MONTANT               DECIMAL(22,2) NOT NULL,
	DEVISE_ID             VARCHAR(3) NULL
)
;



ALTER TABLE TRANCHE_PAIMENT_PARAM
	ADD  PRIMARY KEY (NO_SEQ)
;



CREATE UNIQUE INDEX TRANCHPAIEPAR_ROWID_UQ ON TRANCHE_PAIMENT_PARAM
(
	ROWID
)
;



CREATE TABLE TRANSACTION
(
	TRANSACTION_NO        INTEGER NOT NULL DEFAULT 0,
	DESCRIPTION           VARCHAR(100) NOT NULL,
	DATE_TRANSACTION      TIMESTAMP NOT NULL,
	SIGNE                 INTEGER NOT NULL DEFAULT 1,
	MONTANT               DATE NULL,
	ORIGINE               VARCHAR(30) NOT NULL,
	REFERENCE_NO          INTEGER NOT NULL DEFAULT 0,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	TYPE_TRANSACTION      CHAR(18) NULL,
	DEVISE_ID             VARCHAR(3) NULL,
	CHEQUE_NO             VARCHAR(20) NULL,
	LINK_TRANSACTION_NO   INTEGER NULL
)
;



ALTER TABLE TRANSACTION
	ADD  PRIMARY KEY (TRANSACTION_NO)
;



CREATE TABLE TYPE_DOCUMENT
(
	TYPE_DOCUMENT         VARCHAR(20) NULL,
	DESCRIPTION           VARCHAR(60) NOT NULL,
	OBLIGATOIRE           VARCHAR(20) NOT NULL DEFAULT 'Y'
		CONSTRAINT  OBLIGATOIRE CHECK (OBLIGATOIRE IN('Y','N')),
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL
)
;



ALTER TABLE TYPE_DOCUMENT
	ADD  PRIMARY KEY (TYPE_DOCUMENT)
;



CREATE TABLE TYPE_TRANSACTION
(
	TYPE_TRANSACTION      CHAR(18) NULL,
	SIGNE                 INTEGER NOT NULL DEFAULT 1,
	DESCRIPTION           VARCHAR(60) NOT NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0
)
;



ALTER TABLE TYPE_TRANSACTION
	ADD  PRIMARY KEY (TYPE_TRANSACTION)
;



CREATE TABLE USER_GROUP
(
	USER_GROUP_ID         VARCHAR(20) NULL,
	DESCRIPTION           VARCHAR(20) NULL,
	ACTIF                 VARCHAR(20) NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0
)
;



ALTER TABLE USER_GROUP
	ADD  PRIMARY KEY (USER_GROUP_ID)
;



CREATE UNIQUE INDEX USER_GROUP_ROWID_UQ ON USER_GROUP
(
	ROWID
)
;



CREATE INDEX UGROUP_CUSER_IX ON USER_GROUP
(
	CREATED_BY
)
;



CREATE INDEX UGROUP_CDATE_IX ON USER_GROUP
(
	CREATED_ON
)
;



CREATE TABLE USER_GROUP_DETAIL
(
	USER_GROUP_ID         VARCHAR(20) NOT NULL,
	ECRAN                 VARCHAR(120) NOT NULL,
	VISUALISER            VARCHAR(1) NOT NULL DEFAULT 'N',
	CREER                 VARCHAR(1) NOT NULL DEFAULT 'N',
	MODIFIER              VARCHAR(1) NOT NULL DEFAULT 'N',
	SUPPRIMER             VARCHAR(1) NOT NULL DEFAULT 'N',
	TRAITER               VARCHAR(1) NOT NULL DEFAULT 'N'
		CONSTRAINT  TRAITER CHECK (MODIFIER IN('Y','N')),
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	LIBELLE               VARCHAR(120) NOT NULL,
	FILTRER_UTILISATEUR   VARCHAR(1) NOT NULL DEFAULT 'N',
	FILTRER_INSTITUTION   VARCHAR(1) NOT NULL DEFAULT 'Y'
		CONSTRAINT  FILTRER_INSTITUTION CHECK (FILTRER_INSTITUTION IN('Y','N')),
	FILTRER_GROUPE        VARCHAR(1) NOT NULL DEFAULT 'N'
		CONSTRAINT  FILTRER_GROUPE CHECK (FILTRER_UTILISATEUR IN('Y','N')),
	BESOIN_AUTOR          VARCHAR(20) NULL DEFAULT 'N'
		CONSTRAINT  BESOIN_AUTOR CHECK (BESOIN_AUTOR IN('Y','N')),
	MONTANT_MAX_AUTOR     INTEGER NULL DEFAULT 0
)
;



ALTER TABLE USER_GROUP_DETAIL
	ADD  PRIMARY KEY (USER_GROUP_ID,ECRAN)
;



CREATE UNIQUE INDEX USER_GROUPDT_ROWID_UQ ON USER_GROUP_DETAIL
(
	ROWID
)
;



CREATE UNIQUE INDEX UGROUP_CDATE_IX ON USER_GROUP_DETAIL
(
	CREATED_ON
)
;



CREATE INDEX UGROUP_CUSER_IX ON USER_GROUP_DETAIL
(
	CREATED_BY
)
;



CREATE TABLE USER_PROFILE
(
	USER_ID               VARCHAR(20) NULL,
	TITLE                 VARCHAR(20) NOT NULL,
	FIRST_NAME            VARCHAR(50) NOT NULL,
	LAST_NAME             VARCHAR(40) NOT NULL,
	STATUS                VARCHAR(20) NOT NULL,
	SEX                   VARCHAR(6) NOT NULL,
	LANGUAGE              VARCHAR(20) NOT NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	CREATED_ON            DATE NOT NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	INSTITUTION_ID        INTEGER NULL,
	USER_GROUP_ID         int(11) NULL,
	PIN_CODE              VARCHAR(128) NULL,
	EXPIRATION_DATE       DATE NULL,
	EMAIL                 VARCHAR(50) NULL,
	INACTIVITY_DELAY      VARCHAR(20) NULL,
	CURRENT_CONNECTION    DATETIME NULL,
	LAST_CONNECTIONN      DATETIME NULL,
	ROLE_LEVEL            VARCHAR(20) NULL
		CONSTRAINT  ROLE_LEVEL CHECK (ROLE_LEVEL IN('CAISSIER','ADMIN')),
	MARK_ACCESS           VARCHAR(20) NOT NULL DEFAULT 'N'
		CONSTRAINT  MARK_ACCESS CHECK (MARK_ACCESS IN('Y','N')),
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	ROWID                 VARCHAR(128) NOT NULL
)
;



ALTER TABLE USER_PROFILE
	ADD  PRIMARY KEY (USER_ID)
;



CREATE UNIQUE INDEX USER_PROFILE_ROWID_UQ ON USER_PROFILE
(
	ROWID
)
;



CREATE UNIQUE INDEX USER_PROFILE_INST_IX ON USER_PROFILE
(
	INSTITUTION_ID
)
;



CREATE INDEX USER_PROFILE_NOM_IX ON USER_PROFILE
(
	FIRST_NAME,
	LAST_NAME
)
;



CREATE INDEX USER_PROFILE_STATUT_IX ON USER_PROFILE
(
	STATUS
)
;



CREATE INDEX UPROFILE_CDATE_IX ON USER_PROFILE
(
	CREATED_ON
)
;



CREATE INDEX UPROFILE_CUSER_IX ON USER_PROFILE
(
	CREATED_BY
)
;



CREATE TABLE VACATION
(
	CODE_VACATION         VARCHAR(20) NOT NULL,
	DESCRIPTION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0
)
;



ALTER TABLE VACATION
	ADD  PRIMARY KEY (CODE_VACATION)
;



CREATE UNIQUE INDEX VACAT_ROWID_UQ ON VACATION
(
	ROWID
)
;



CREATE TABLE VILLE
(
	CODE_VILLE            VARCHAR(20) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	ROWID                 VARCHAR(128) NOT NULL,
	UPDATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NOT NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	NOM                   VARCHAR(20) NOT NULL,
	CODE_ETAT             VARCHAR(20) NOT NULL,
	CODE_PAYS             VARCHAR(20) NOT NULL
)
;



ALTER TABLE VILLE
	ADD  PRIMARY KEY (CODE_VILLE,CODE_ETAT,CODE_PAYS)
;



CREATE UNIQUE INDEX VILLE_ROWID_UQ ON VILLE
(
	ROWID
)
;



ALTER TABLE AFFECTATION_COURS
	ADD FOREIGN KEY ENSEIGNANT_AFFECTC_FK (CODE_ENSEIGNANT) REFERENCES ENSEIGNANT(CODE_ENSEIGNANT)
;


ALTER TABLE AFFECTATION_COURS
	ADD FOREIGN KEY COURS_AFFECTC_FK (CODE_COURS) REFERENCES COURS(CODE_COURS)
;


ALTER TABLE AFFECTATION_COURS
	ADD FOREIGN KEY VACATION_AFFECTC_FK (CODE_VACATION) REFERENCES VACATION(CODE_VACATION)
;


ALTER TABLE AFFECTATION_COURS
	ADD FOREIGN KEY DEVISE_AFF_COURS_FK (DEVISE_ID) REFERENCES DEVISE(DEVISE_ID)
;



ALTER TABLE APPRENANT
	ADD FOREIGN KEY VILLE_APPRENANT1_FK (CODE_VILLE_NAISSANCE,CODE_ETAT_NAISSANCE,CODE_PAYS_NAISSANCE) REFERENCES VILLE(CODE_VILLE,CODE_ETAT,CODE_PAYS)
;


ALTER TABLE APPRENANT
	ADD FOREIGN KEY VILLE_APPRENANT2_FK (CODE_VILLE_HABITATION,CODE_ETAT_HABITATION,CODE_PAYS_HABITATION) REFERENCES VILLE(CODE_VILLE,CODE_ETAT,CODE_PAYS)
;



ALTER TABLE AUTORISATION
	ADD FOREIGN KEY UPROF_AUTORISATION_FK (USER_ID) REFERENCES USER_PROFILE(USER_ID)
;



ALTER TABLE CHOIX_COURS
	ADD FOREIGN KEY APPRENANT_CBXCOURS_FK (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;


ALTER TABLE CHOIX_COURS
	ADD FOREIGN KEY COURS_CBXCOURS_FK (CODE_COURS) REFERENCES COURS(CODE_COURS)
;



ALTER TABLE COURS
	ADD FOREIGN KEY MATIERE_COURS_FK (CODE_MATIERE) REFERENCES MATIERE(CODE_MATIERE)
;


ALTER TABLE COURS
	ADD FOREIGN KEY NIVEAU_COURS_FK (CODE_NIVEAU) REFERENCES NIVEAU(CODE_NIVEAU)
;


ALTER TABLE COURS
	ADD FOREIGN KEY COURS_PREREQUIS_FK (CODE_COURS) REFERENCES COURS(CODE_COURS)
;


ALTER TABLE COURS
	ADD FOREIGN KEY OPTION_COURS_FK (CODE_OPTION) REFERENCES OPTION(CODE_OPTION)
;



ALTER TABLE DOCUMENT_FOURNI
	ADD FOREIGN KEY R_145 (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;


ALTER TABLE DOCUMENT_FOURNI
	ADD FOREIGN KEY R_146 (TYPE_DOCUMENT) REFERENCES TYPE_DOCUMENT(TYPE_DOCUMENT)
;



ALTER TABLE ENSEIGNANT
	ADD FOREIGN KEY DEVISE_ENSEIG_FK (DEVISE_ID) REFERENCES DEVISE(DEVISE_ID)
;



ALTER TABLE ETAT
	ADD FOREIGN KEY PAYS_ETAT_FK (CODE_PAYS) REFERENCES PAYS(CODE_PAYS)
;



ALTER TABLE ETUDE_ANTERIEURE
	ADD FOREIGN KEY APPRENANT_ETANT_FK (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;



ALTER TABLE INSTITUTION
	ADD FOREIGN KEY R_46 (DEVISE_LOCALE) REFERENCES DEVISE(DEVISE_ID)
;



ALTER TABLE NIVEAU
	ADD FOREIGN KEY DEVISE_NIVEAU_FK (DEVISE_ID) REFERENCES DEVISE(DEVISE_ID)
;



ALTER TABLE PACOURS_APPRENANT
	ADD FOREIGN KEY APPRENANT_NIVEAU_FK (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;


ALTER TABLE PACOURS_APPRENANT
	ADD FOREIGN KEY NIVEAU_PACOURS_FK (CODE_NIVEAU) REFERENCES NIVEAU(CODE_NIVEAU)
;


ALTER TABLE PACOURS_APPRENANT
	ADD FOREIGN KEY SALLE_PACOURS_FK (CODE_SALLE) REFERENCES SALLE(CODE_SALLE)
;


ALTER TABLE PACOURS_APPRENANT
	ADD FOREIGN KEY VACATION_PACOURS_FK (CODE_VACATION) REFERENCES VACATION(CODE_VACATION)
;


ALTER TABLE PACOURS_APPRENANT
	ADD FOREIGN KEY OPTION_PACOURS_FK (CODE_OPTION) REFERENCES OPTION(CODE_OPTION)
;



ALTER TABLE PAIEMENT
	ADD FOREIGN KEY APPRENANT_PAIE_FK (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;


ALTER TABLE PAIEMENT
	ADD FOREIGN KEY DEVISE_PAIE_FK (DEVISE_ID) REFERENCES DEVISE(DEVISE_ID)
;



ALTER TABLE SUIVI_APPRENANT
	ADD FOREIGN KEY APPRENANT_AUINF_FK (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;



ALTER TABLE TAUX
	ADD FOREIGN KEY R_44 (DEVISE_ID) REFERENCES DEVISE(DEVISE_ID)
;



ALTER TABLE TRANCHE_PAIMENT_PARAM
	ADD FOREIGN KEY NIVEAU_TRANCHE_PAIEMENT_CK (CODE_NIVEAU) REFERENCES NIVEAU(CODE_NIVEAU)
;


ALTER TABLE TRANCHE_PAIMENT_PARAM
	ADD FOREIGN KEY VACATION_PAIEPAR_FK (CODE_VACATION) REFERENCES VACATION(CODE_VACATION)
;


ALTER TABLE TRANCHE_PAIMENT_PARAM
	ADD FOREIGN KEY DEVISE_TRANCHE_FK (DEVISE_ID) REFERENCES DEVISE(DEVISE_ID)
;



ALTER TABLE TRANSACTION
	ADD FOREIGN KEY R_92 (TYPE_TRANSACTION) REFERENCES TYPE_TRANSACTION(TYPE_TRANSACTION)
;


ALTER TABLE TRANSACTION
	ADD FOREIGN KEY R_96 (DEVISE_ID) REFERENCES DEVISE(DEVISE_ID)
;


ALTER TABLE TRANSACTION
	ADD FOREIGN KEY R_102 (TRANSACTION_NO) REFERENCES TRANSACTION(TRANSACTION_NO)
;



ALTER TABLE USER_GROUP_DETAIL
	ADD FOREIGN KEY R_62 (USER_GROUP_ID) REFERENCES USER_GROUP(USER_GROUP_ID)
;



ALTER TABLE USER_PROFILE
	ADD FOREIGN KEY R_5 (INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID)
;


ALTER TABLE USER_PROFILE
	ADD FOREIGN KEY R_6 (USER_GROUP_ID) REFERENCES USER_GROUP(USER_GROUP_ID)
;



ALTER TABLE VILLE
	ADD FOREIGN KEY ETAT_VILLE_FK (CODE_ETAT,CODE_PAYS) REFERENCES ETAT(CODE_ETAT,CODE_PAYS)
;
