
CREATE TABLE APPRENANT
(
	CODE_APPRENANT        varchar(20) NOT NULL,
	DATE_INSCRIPTION      date NULL,
	DATE_NAISSANCE        date NOT NULL,
	ETAT_CIVIL            varchar(1) NOT NULL,
	SEXE                  varchar(1) NOT NULL,
	STATUT                varchar(20) NOT NULL,
	NOM_PERE              varchar(50) NULL,
	NOM_MERE              varchar(50) NULL,
	NOM_CONJOINT          varchar(50) NULL,
	PIECE                 varchar(15) NOT NULL,
	NO_PIECE              varchar(40) NOT NULL,
	TELEPHONE_1           varchar(25) NOT NULL,
	TELEPHONE_2           varchar(25) NULL,
	TELEPHONE_3           varchar(25) NULL,
	COURRIEL              varchar(40) NULL,
	NATIONALITE           varchar(15) NULL,
	NOM                   varchar(30) NOT NULL,
	NOM_JEUNE_FILLE       varchar(30) NULL,
	PRENOM                varchar(30) NOT NULL,
	ADRESSE               varchar(75) NULL,
	REMARQUE              varchar(128) NULL,
	ADRESSE_POSTALE       varchar(75) NULL,
	AUTRE_INFORMATION     varchar(2000) NULL,
	LOCALISATION          varchar(100) NULL,
	PERSONNE_CONTACT      varchar(50) NULL,
	TELEPHONE_CONTACT     varchar(50) NULL,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWSCN                INTEGER NOT NULL,
	ROWID                 varchar(128) NOT NULL,
	PHOTO                 VARCHAR(200) NULL,
	MOYEN_TRANSPORT       VARCHAR(20) NULL
		CONSTRAINT  MOYEN_TRANSPORT CHECK (MOYEN_TRANSPORT IN('PUBLIC','VOITURE','MOTO','VELO','PIED','AUTRE')),
	NO_BADGE              VARCHAR(20) NULL,
	COURRIEL_ALT          VARCHAR(20) NULL,
	CODE_VILLE_NAISSANCE  VARCHAR(20) NULL,
	CODE_ETAT_NAISSANCE   VARCHAR(20) NULL,
	CODE_PAYS_NAISSANCE   VARCHAR(20) NULL,
	CODE_VILLE_HABITATION  VARCHAR(20) NULL,
	CODE_ETAT_HABITATION  VARCHAR(20) NULL,
	CODE_PAYS_HABITATION  VARCHAR(20) NULL
)
;



ALTER TABLE APPRENANT
	ADD  PRIMARY KEY (CODE_APPRENANT)
;



CREATE UNIQUE INDEX EMPLOYE_ROWID_UQ ON APPRENANT
(
	ROWID
)
;



CREATE TABLE CHOIX_COURS
(
	CODE_APPRENANT        varchar(20) NOT NULL,
	DATE_CHOIX            DATE NULL,
	CODE_COURS            VARCHAR(20) NOT NULL,
	MENTION               VARCHAR(60) NULL,
	NOTE                  DECIMAL(22,2) NOT NULL DEFAULT 0,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL,
	COEFFICIENT           INTEGER NOT NULL DEFAULT 1,
	CODE_NIVEAU           VARCHAR(20) NOT NULL
)
;



ALTER TABLE CHOIX_COURS
	ADD  PRIMARY KEY (CODE_APPRENANT,CODE_COURS)
;



CREATE TABLE COURS
(
	CODE_COURS            VARCHAR(20) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	CODE_MATIERE          VARCHAR(20) NULL,
	COEFFICIENT           INTEGER NOT NULL DEFAULT 1,
	OBLIGATOIRE           VARCHAR(20) NULL DEFAULT 'Y'
		CONSTRAINT  OBLIGATOIRE CHECK (OBLIGATOIRE IN('Y','N')),
	ACTIF                 VARCHAR(1) NOT NULL DEFAULT 'Y'
		CONSTRAINT  ACTIF CHECK (ACTIF IN('Y','N')),
	DATE_CREATION         DATE NOT NULL,
	DATE_STATUT           DATE NULL,
	NB_CREDIT             INTEGER NOT NULL DEFAULT 0,
	PREREQUIS             VARCHAR(20) NULL,
	CODE_OPTION           VARCHAR(20) NULL
)
;



ALTER TABLE COURS
	ADD  PRIMARY KEY (CODE_COURS)
;



CREATE UNIQUE INDEX COURS_ROWID_UQ ON COURS
(
	ROWID
)
;



CREATE TABLE DOCUMENT_FOURNI
(
	DATE_RECEPTION        DATE NULL,
	REMARQUE              VARCHAR(100) NULL,
	CODE_APPRENANT        varchar(20) NOT NULL,
	TYPE_DOCUMENT         VARCHAR(20) NOT NULL,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL,
	DOCUMENT              VARCHAR(256) NOT NULL
)
;



ALTER TABLE DOCUMENT_FOURNI
	ADD  PRIMARY KEY (CODE_APPRENANT,TYPE_DOCUMENT)
;



CREATE TABLE ETUDE_ANTERIEURE
(
	DATE_DEBUT            date NOT NULL,
	DATE_FIN              date NOT NULL,
	TITRE                 varchar(100) NOT NULL,
	ETABLISSEMENT         varchar(100) NOT NULL,
	REMARQUE              varchar(100) NULL,
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWSCN                INTEGER NOT NULL,
	ROWID                 varchar(128) NOT NULL,
	NO_SEQ                INTEGER NULL,
	CODE_APPRENANT        varchar(20) NOT NULL,
	SUCCES                VARCHAR(20) NOT NULL DEFAULT 'Y'
		CONSTRAINT  SUCCES CHECK (SUCCESS IN('Y','N')),
	MOYENNE               DECIMAL(22,2) NOT NULL DEFAULT 0,
	MOYENNE_PASSAGE       DECIMAL(22,2) NULL
)
;



ALTER TABLE ETUDE_ANTERIEURE
	ADD  PRIMARY KEY (DATE_DEBUT,DATE_FIN,NO_SEQ,CODE_APPRENANT)
;



CREATE UNIQUE INDEX FORMATION_ROWID_UQ ON ETUDE_ANTERIEURE
(
	ROWID
)
;



CREATE TABLE NIVEAU
(
	DESIGNATION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	OPTION_PAIEMENT       CHAR(18) NULL DEFAULT 'TRANCHE'
		CONSTRAINT  OPTION_PAIEMENT CHECK (MODE_PAIEMENT IN('CREDIT','MENSUEL','TRANCHE','TRIMESTRIEL','SEMESTRIEL','ANNUEL')),
	MONTANT_OBLIGATION    DECIMAL(22,2) NOT NULL DEFAULT 0,
	DATE_PAIEM_OBLIGATION  DATE NULL,
	DEVISE_ID             VARCHAR(3) NULL,
	NO_SEQ                INTEGER NOT NULL
)
;



CREATE UNIQUE INDEX NIVEAU_ROWID_UQ ON NIVEAU
(
	ROWID
)
;



CREATE UNIQUE INDEX NIVEAU_SEQ_IX ON NIVEAU
(
	NO_SEQ
)
;



CREATE TABLE OPTION
(
	DESIGNATION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	CODE_OPTION           VARCHAR(20) NOT NULL
)
;



ALTER TABLE OPTION
	ADD  PRIMARY KEY (CODE_OPTION)
;



CREATE UNIQUE INDEX OPTION_ROWID_UQ ON OPTION
(
	ROWID
)
;



CREATE TABLE PACOURS_APPRENANT
(
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL,
	DATE_DEBUT            DATE NULL,
	DATE_FIN              DATE NULL,
	CODE_APPRENANT        varchar(20) NOT NULL,
	CODE_SALLE            VARCHAR(20) NULL,
	CODE_VACATION         VARCHAR(20) NULL,
	CODE_OPTION           VARCHAR(20) NULL,
	ACTIF                 VARCHAR(1) NOT NULL DEFAULT 'N'
		CONSTRAINT  ACTIF CHECK (ACTIF IN('Y','N')),
	REMARQUES             VARCHAR(1000) NULL
)
;



ALTER TABLE PACOURS_APPRENANT
	ADD  PRIMARY KEY (CODE_APPRENANT,DATE_DEBUT)
;



CREATE TABLE SALLE
(
	CODE_SALLE            VARCHAR(20) NOT NULL,
	DESCRIPTION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0
)
;



ALTER TABLE SALLE
	ADD  PRIMARY KEY (CODE_SALLE)
;



CREATE UNIQUE INDEX SALLE_ROWID_UQ ON SALLE
(
	ROWID
)
;



CREATE TABLE SUIVI_APPRENANT
(
	NO_SEQ                INTEGER NOT NULL,
	REMARQUE              VARCHAR(2000) NOT NULL,
	GRAVITE               VARCHAR(20) NOT NULL DEFAULT 'NEUTRE'
		CONSTRAINT  GRAVITE CHECK (GRAVITE IN('NEUTRE','GRAVE','MOYEN','PAS GRAVE')),
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWSCN                INTEGER NOT NULL,
	ROWID                 varchar(128) NOT NULL,
	DATE_INFO             DATE NOT NULL,
	CODE_APPRENANT        varchar(20) NULL
)
;



ALTER TABLE SUIVI_APPRENANT
	ADD  PRIMARY KEY (NO_SEQ)
;



CREATE UNIQUE INDEX AUTREINF_ROWID_UQ ON SUIVI_APPRENANT
(
	ROWID
)
;



CREATE TABLE TYPE_DOCUMENT
(
	TYPE_DOCUMENT         VARCHAR(20) NULL,
	DESCRIPTION           VARCHAR(60) NOT NULL,
	OBLIGATOIRE           VARCHAR(20) NOT NULL DEFAULT 'Y'
		CONSTRAINT  OBLIGATOIRE CHECK (OBLIGATOIRE IN('Y','N')),
	CREATED_BY            varchar(30) NOT NULL,
	CREATED_ON            TIMESTAMP NOT NULL,
	UPDATED_BY            varchar(30) NULL,
	UPDATED_ON            TIMESTAMP NULL,
	ROWID                 varchar(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL
)
;



ALTER TABLE TYPE_DOCUMENT
	ADD  PRIMARY KEY (TYPE_DOCUMENT)
;



CREATE TABLE VACATION
(
	CODE_VACATION         VARCHAR(20) NOT NULL,
	DESCRIPTION           VARCHAR(100) NOT NULL,
	CREATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	UPDATED_ON            DATE NULL,
	ROWID                 VARCHAR(128) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0
)
;



ALTER TABLE VACATION
	ADD  PRIMARY KEY (CODE_VACATION)
;



CREATE UNIQUE INDEX VACAT_ROWID_UQ ON VACATION
(
	ROWID
)
;



CREATE TABLE VILLE
(
	CODE_VILLE            VARCHAR(20) NOT NULL,
	ROWSCN                INTEGER NOT NULL DEFAULT 0,
	ROWID                 VARCHAR(128) NOT NULL,
	UPDATED_ON            DATE NULL,
	UPDATED_BY            VARCHAR(20) NULL,
	CREATED_ON            DATE NOT NULL,
	CREATED_BY            VARCHAR(20) NOT NULL,
	NOM                   VARCHAR(20) NOT NULL,
	CODE_ETAT             VARCHAR(20) NOT NULL,
	CODE_PAYS             VARCHAR(20) NOT NULL
)
;



ALTER TABLE VILLE
	ADD  PRIMARY KEY (CODE_VILLE,CODE_ETAT,CODE_PAYS)
;



CREATE UNIQUE INDEX VILLE_ROWID_UQ ON VILLE
(
	ROWID
)
;



ALTER TABLE APPRENANT
	ADD FOREIGN KEY VILLE_APPRENANT1_FK (CODE_VILLE_NAISSANCE,CODE_ETAT_NAISSANCE,CODE_PAYS_NAISSANCE) REFERENCES VILLE(CODE_VILLE,CODE_ETAT,CODE_PAYS)
;


ALTER TABLE APPRENANT
	ADD FOREIGN KEY VILLE_APPRENANT2_FK (CODE_VILLE_HABITATION,CODE_ETAT_HABITATION,CODE_PAYS_HABITATION) REFERENCES VILLE(CODE_VILLE,CODE_ETAT,CODE_PAYS)
;



ALTER TABLE CHOIX_COURS
	ADD FOREIGN KEY APPRENANT_CBXCOURS_FK (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;


ALTER TABLE CHOIX_COURS
	ADD FOREIGN KEY COURS_CBXCOURS_FK (CODE_COURS) REFERENCES COURS(CODE_COURS)
;



ALTER TABLE COURS
	ADD FOREIGN KEY MATIERE_COURS_FK (CODE_MATIERE) REFERENCES MATIERE(CODE_MATIERE)
;


ALTER TABLE COURS
	ADD FOREIGN KEY COURS_PREREQUIS_FK (CODE_COURS) REFERENCES COURS(CODE_COURS)
;


ALTER TABLE COURS
	ADD FOREIGN KEY OPTION_COURS_FK (CODE_OPTION) REFERENCES OPTION(CODE_OPTION)
;



ALTER TABLE DOCUMENT_FOURNI
	ADD FOREIGN KEY R_145 (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;


ALTER TABLE DOCUMENT_FOURNI
	ADD FOREIGN KEY R_146 (TYPE_DOCUMENT) REFERENCES TYPE_DOCUMENT(TYPE_DOCUMENT)
;



ALTER TABLE ETUDE_ANTERIEURE
	ADD FOREIGN KEY APPRENANT_ETANT_FK (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;



ALTER TABLE NIVEAU
	ADD FOREIGN KEY DEVISE_NIVEAU_FK (DEVISE_ID) REFERENCES DEVISE(DEVISE_ID)
;



ALTER TABLE PACOURS_APPRENANT
	ADD FOREIGN KEY APPRENANT_NIVEAU_FK (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;


ALTER TABLE PACOURS_APPRENANT
	ADD FOREIGN KEY SALLE_PACOURS_FK (CODE_SALLE) REFERENCES SALLE(CODE_SALLE)
;


ALTER TABLE PACOURS_APPRENANT
	ADD FOREIGN KEY VACATION_PACOURS_FK (CODE_VACATION) REFERENCES VACATION(CODE_VACATION)
;


ALTER TABLE PACOURS_APPRENANT
	ADD FOREIGN KEY OPTION_PACOURS_FK (CODE_OPTION) REFERENCES OPTION(CODE_OPTION)
;



ALTER TABLE SUIVI_APPRENANT
	ADD FOREIGN KEY APPRENANT_AUINF_FK (CODE_APPRENANT) REFERENCES APPRENANT(CODE_APPRENANT)
;



ALTER TABLE VILLE
	ADD FOREIGN KEY ETAT_VILLE_FK (CODE_ETAT,CODE_PAYS) REFERENCES ETAT(CODE_ETAT,CODE_PAYS)
;
